### ISSUE TITLE
Error when create arm-rent

### ISSUE THREAD

**Issue by RubenStryker** [alex9849/advancedregionmarket#1]
Server version: Spigot 1.13.2
Plugin version: AdvancedRegionMarket 1.5.1
WorldGuard Version: WorldGuard v7.0.0-SNAPSHOT;0dc5781

When I create the poster, so that it does its rental function, I miss the following error:

`[12:23:14] [Server thread/ERROR]: Could not pass event BlockBreakEvent to AdvancedRegionMarket v1.5.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[paper.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper.jar:git-Spigot-2474d93-e693496]
	at com.heirteir.perworldpluginspremium.registeredlisteners.BukkitRegisteredListener.callEvent(BukkitRegisteredListener.java:35) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[paper.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:219) ~[paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1183) ~[paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[paper.jar:git-Spigot-2474d93-e693496]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [paper.jar:git-Spigot-2474d93-e693496]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
	at net.alex9849.adapters.WorldGuard7.canBuild(WorldGuard7.java:79) ~[?:?]
	at net.alex9849.arm.Handler.ARMListener.breakBlock(ARMListener.java:398) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[paper.jar:git-Spigot-2474d93-e693496]
	... 18 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.math.BlockVector3
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[paper.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[paper.jar:git-Spigot-2474d93-e693496]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at net.alex9849.adapters.WorldGuard7.canBuild(WorldGuard7.java:79) ~[?:?]
	at net.alex9849.arm.Handler.ARMListener.breakBlock(ARMListener.java:398) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[paper.jar:git-Spigot-2474d93-e693496]
	... 18 more`

**Comment by alex9849** [comment]
Have you installed the newest version of worldguard?
https://dev.bukkit.org/projects/worldguard/files

**Comment by RubenStryker** [comment]
The same thing is happening.v

**Comment by alex9849** [comment]
Have you also installed the newest worldedit beta build?

**Comment by RubenStryker** [comment]
I use FAWE... https://empcraft.com/fawe/download/

**Comment by alex9849** [comment]
Ah ok. FaWe still uses the old WorldGaurd libarys. I think they'll update them soon.
As soon as they update them I'll release a new version, that supports FaWe.
For the time till the new FaWe release you can just use the original WorldGaurd and WorldEdit files.
